{% set name = "RESTinstance" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c61a5d791f65bda69cc63dc84889ecd9dd7e64ec1e92423a4d7949ad3957642

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - robotframework
    - docutils
    - pyyaml
    - flex-swagger
    - genson
    - jsonpath-ng
    - pygments
    - requests
    - jsonschema
    - rfc3987
    - strict-rfc3339
    - pytz
    - tzlocal

test:
  imports:
    - REST

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
