{% set version = "1.3.0" %}

package:
  name: restinstance
  version: {{ version }}

source:
  # TODO: restore after https://github.com/asyrjasalo/RESTinstance/issues/127
  # url: https://pypi.io/packages/source/R/RESTinstance/RESTinstance-{{ version }}.tar.gz
  url: https://github.com/asyrjasalo/RESTinstance/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7a1cb842604d3132c0c803870e6e8008b521717dc7f72b379d268e74673dda0c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - docutils
    - flex-swagger
    - genson
    - jsonpath-ng
    - jsonschema
    - pygments
    - python >=3.6
    - pytz
    - pyyaml
    - requests
    - robotframework
    - tzlocal

test:
  requires:
    - pip
    # TODO: revist after https://github.com/conda-forge/flex-swagger-feedstock/pull/8
    - python <3.10
  imports:
    - REST
  commands:
    - pip check

about:
  home: https://github.com/asyrjasalo/RESTinstance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework library for RESTful JSON APIs

extra:
  recipe-maintainers:
    - abloemert
    - bollwyvl
